# Rename this file to languages.toml to enable multilingual support
[languages]
  [en]
    contentDir = 'content/en'
    languageName = 'English'
    languagedirection = 'ltr'
    title = 'Pablo Leon Rodrigues'
    weight = 1
      [en.params.sidebar]
        subtitle = 'Software Engineer, Learning how to paint miniatures, D&D Dungeon Master for my friends, casual MTG player'

  [pt-br]
    contentDir = 'content/pt-br'
    languageName = 'Português'
    languagedirection = 'ltr'
    title = 'Pablo Leon Rodrigues'
    weight = 1
      [pt-br.params.sidebar]
        subtitle = 'Engenheiro de Software, Aprendendo a pintar miniaturas, D&D Dungeon Master para meus amigos, jogador casual de MTG'

