# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true
[[social]]
identifier = "email"
name = "Email"
url = "mailto:pablo.leonrodrigues@gmail.com"

[social.params]
icon = "mail"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/pleonr"

[social.params]
icon = "brand-github"

[[social]]
identifier = "reddit"
name = "Reddit"
url = "https://www.reddit.com/user/leonpf"

[social.params]
icon = "brand-reddit"

[[social]]
identifier = "steam"
name = "Steam"
url = "https://steamcommunity.com/id/leonpf"

[social.params]
icon = "brand-steam"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/pablo.leonrodrigues"

[social.params]
icon = "brand-instagram"
